name: Deploy to Cloud

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - 'apps/example/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.19.0'
          cache: 'npm'

      - name: Install MakePages
        run: npm install -g makepages

      - name: Build website
        run: cd apps/example && npm install && npm run build

      - name: Deploy to Netlify
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        run: |
          npm install -g netlify-cli
          netlify deploy --filter=example --site $NETLIFY_SITE_ID --auth $NETLIFY_AUTH_TOKEN --prod --dir=./apps/example/dist

      - name: Deploy to Vercel
        run: |
          npm install -g vercel
          vercel deploy --yes --project makepages --yes --prod --cwd ./apps/example/dist/ --token ${{ secrets.VERCEL_TOKEN }}

      - name: Deploy to Cloudflare Pages
        env:
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        run: npx wrangler pages deploy ./apps/example/dist --project-name makepages